import { createClient } from "npm:@supabase/supabase-js@2.39.3";
import { PDFDocument, StandardFonts, rgb } from "npm:pdf-lib";

const corsHeaders={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"GET, OPTIONS"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json",...corsHeaders}});
const normalizarClave=(v:string|null|undefined)=>{const x=String(v||"REGISTRO").trim().toUpperCase();return x==="RENOVACIÓN"?"RENOVACION":x};
const codigoConcepto=(tipo:"profesional"|"establecimiento",clave:string)=>tipo==="profesional"&&clave==="REGISTRO"?"REG_PROFESIONAL_SANITARIO":tipo==="establecimiento"&&clave==="REGISTRO"?"REG_ESTABLECIMIENTO_SANITARIO":tipo==="establecimiento"&&clave==="RENOVACION"?"RENOVACION_LICENCIA_ESTABLECIMIENTO":null;

Deno.serve(async(req:Request)=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:corsHeaders});
 if(req.method!=="GET")return json({error:"Método no permitido"},405);
 const url=new URL(req.url);const tipo=url.searchParams.get("tipo") as "profesional"|"establecimiento"|null;const solicitudId=url.searchParams.get("id");
 if(!tipo||!solicitudId||!["profesional","establecimiento"].includes(tipo))return json({error:'Parámetros "tipo" e "id" son requeridos'},400);
 const db=createClient(Deno.env.get("SUPABASE_URL")??"",Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??"");
 try{
  const {data:existing}=await db.from("notas_ingreso").select("*").eq("solicitud_id",solicitudId).eq("tipo_solicitud",tipo).maybeSingle();if(existing)return json({success:true,message:"Nota de ingreso ya generada previamente",nota:existing});
  let nombre="",documento="",clave="REGISTRO";
  if(tipo==="profesional"){
   const {data:p,error}=await db.from("profesionales_sanitarios").select("id,nombre_completo,numero_dip,id_profesional_unico,estado_solicitud,tipo_solicitud").eq("id",solicitudId).single();if(error||!p)return json({error:"Profesional no encontrado",details:error?.message},404);if(p.estado_solicitud!=="Aprobado")return json({error:"El profesional no está en estado Aprobado"},400);nombre=p.nombre_completo||"";documento=p.numero_dip||p.id_profesional_unico||"";clave=normalizarClave(p.tipo_solicitud);
  }else{
   const {data:e,error}=await db.from("solicitudes_establecimientos").select("id,nombre_establecimiento,nif,numero_documento,estado,tipo_solicitud").eq("id",solicitudId).single();if(error||!e)return json({error:"Establecimiento no encontrado",details:error?.message},404);if(e.estado!=="Autorizado")return json({error:"El establecimiento no está en estado Autorizado"},400);nombre=e.nombre_establecimiento||"";documento=e.nif||e.numero_documento||"";clave=normalizarClave(e.tipo_solicitud);
  }
  const codigo=codigoConcepto(tipo,clave);if(!codigo)return json({error:`No existe una plantilla de Nota de Ingreso para ${tipo} / ${clave}. Configure primero ese tipo en el Panel Ministerial.`},422);
  const {data:concepto,error:conceptoError}=await db.from("tesoreria_conceptos").select("*").eq("tipo_solicitud",tipo).eq("clave_solicitud",clave).eq("codigo",codigo).eq("activo",true).single();if(conceptoError||!concepto)return json({error:`Parámetros ministeriales no configurados para ${tipo} / ${clave}`,details:conceptoError?.message},422);if(!String(concepto.cuenta_tesoreria||"").trim())return json({error:`La cuenta de Tesorería no está configurada para ${concepto.descripcion}. Configure el parámetro en el Panel Ministerial antes de emitir la Nota de Ingreso.`},422);
  const {data:num,error:numError}=await db.rpc("generar_numero_nota_ingreso",{p_tipo:tipo});if(numError||!num)return json({error:"Error generando número de nota",details:numError?.message},500);const numeroNota=num as string;
  const payload={numero_nota:numeroNota,tipo_solicitud:tipo,clave_solicitud:clave,solicitud_id:solicitudId,concepto_codigo:concepto.codigo,monto:concepto.monto,moneda:concepto.moneda,cuenta_tesoreria:concepto.cuenta_tesoreria,beneficiario_nombre:nombre,beneficiario_documento:documento,fecha:new Date().toISOString()};
  const {data:sello,error:selloError}=await db.rpc("generar_sello_auditable",{p_tipo_documento:"nota_ingreso",p_documento_id:solicitudId,p_payload:payload,p_generado_por:null});if(selloError||!sello?.length)return json({error:"Error al generar sello auditable",details:selloError?.message},500);const hash:string=sello[0].hash;
  const pdf=await PDFDocument.create();const page=pdf.addPage([595.28,841.89]);const font=await pdf.embedFont(StandardFonts.Helvetica);const bold=await pdf.embedFont(StandardFonts.HelveticaBold);const text=(t:string,x:number,y:number,size=11,b=false)=>page.drawText(t,{x,y,size,font:b?bold:font,color:rgb(0,0,0)});
  text("REPÚBLICA DE GUINEA ECUATORIAL",50,800,13,true);text("MINISTERIO DE SANIDAD E INFRAESTRUCTURAS SANITARIAS",50,784,10);text("Tesorería - Nota de Ingreso",50,768,11);page.drawLine({start:{x:50,y:755},end:{x:545,y:755},thickness:1,color:rgb(0,0,0)});text("NOTA DE INGRESO",50,725,20,true);text(numeroNota,50,700,14,true);
  let y=660;text(`Concepto: ${concepto.descripcion}`,50,y,12);y-=22;text(`Beneficiario: ${nombre}`,50,y,12);y-=22;if(documento){text(`Documento: ${documento}`,50,y,12);y-=22}text(`Monto: ${Number(concepto.monto).toLocaleString("es-ES")} ${concepto.moneda}`,50,y,14,true);y-=22;text(`Cuenta de tesorería: ${concepto.cuenta_tesoreria}`,50,y,12);y-=22;text(`Fecha de emisión: ${new Date().toLocaleDateString("es-ES")}`,50,y,12);y-=40;page.drawLine({start:{x:50,y},end:{x:545,y},thickness:.5,color:rgb(.5,.5,.5)});y-=25;text("SELLO AUDITABLE (HMAC-SHA256)",50,y,10,true);y-=18;text(hash.slice(0,16).toUpperCase(),50,y,11);y-=14;text("Este documento es válido únicamente con su sello auditable.",50,y,9);text("La alteración de cualquier dato invalida el sello.",50,y-12,9);
  const bytes=await pdf.save();const path=`notas-generadas/${numeroNota.replace(/[^a-zA-Z0-9-]/g,"")}_${Date.now()}.pdf`;const {error:uploadError}=await db.storage.from("notas-ingreso").upload(path,bytes,{contentType:"application/pdf",upsert:true});if(uploadError)return json({error:"Error al guardar el PDF",details:uploadError.message},500);const {data:urlPdf}=await db.storage.from("notas-ingreso").getPublicUrl(path);
  const {data:nota,error:insertError}=await db.from("notas_ingreso").insert({numero_nota:numeroNota,tipo_solicitud:tipo,clave_solicitud:clave,solicitud_id:solicitudId,concepto_id:concepto.id,concepto_codigo:concepto.codigo,concepto_descripcion:concepto.descripcion,monto:concepto.monto,moneda:concepto.moneda,cuenta_tesoreria:concepto.cuenta_tesoreria,beneficiario_nombre:nombre,beneficiario_documento:documento,hash,algoritmo:"HMAC-SHA256",pdf_url:urlPdf.publicUrl}).select().single();if(insertError)return json({error:"Error al registrar la nota de ingreso",details:insertError.message},500);
  await db.from("logs_sistema").insert({accion:"GENERACION_NOTA_INGRESO",descripcion:`Nota de ingreso ${numeroNota} generada para ${tipo}/${clave} ID: ${solicitudId} - Hash: ${hash.slice(0,16).toUpperCase()}`,error:false});return json({success:true,message:"Nota de ingreso generada correctamente",nota});
 }catch(error){console.error(error);return json({error:"Error al generar nota de ingreso",details:(error as any)?.message||String(error)},500)}
});
