import { useMemo, useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { ClipboardCheck, Plus, RefreshCw, Save, Search, ShieldCheck } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

const TYPES=["INICIAL","SEGUIMIENTO","EXTRAORDINARIA","RENOVACION"] as const;
const STATES=["PROGRAMADA","EN_CURSO","APROBADA","CONDICIONADA","RECHAZADA","CANCELADA"] as const;
interface Inspection{ id:string;establecimiento_id:string|null;centro_salud_id:string|null;numero_inspeccion:string;tipo_inspeccion:string;estado:string;inspector_id:string|null;fecha_programada:string|null;puntuacion:number|null;resultado:string|null;observaciones:string|null;medidas_correctivas:string|null;plazo_correccion:string|null;created_at:string;centros_salud?:any;solicitudes_establecimientos?:any; }

export default function EstablishmentInspectionsPanel(){
 const {toast}=useToast();const queryClient=useQueryClient();const [selectedId,setSelectedId]=useState("");const [filter,setFilter]=useState("TODOS");const [showNew,setShowNew]=useState(false);const [form,setForm]=useState({centro_salud_id:"",tipo_inspeccion:"INICIAL",fecha_programada:"",observaciones:""});
 const {data:privateCenters=[],isLoading:centersLoading}=useQuery({queryKey:["establecimientos-privados-inspeccion"],queryFn:async()=>{const {data,error}=await supabase.from("centros_salud").select("id,nombre,categoria,subcategoria,provincia,distrito,distrito_sanitario,sector,numero_registro,nif,estado").eq("sector","Privado").order("nombre");if(error)throw error;return data||[];}});
 const {data:inspections=[],isLoading,refetch}=useQuery({queryKey:["inspecciones-establecimientos",filter],queryFn:async()=>{let q=supabase.from("inspecciones_establecimientos").select("*, centros_salud(id,nombre,categoria,provincia,distrito,sector,numero_registro,nif), solicitudes_establecimientos(id,nombre_establecimiento,numero_solicitud,provincia)").order("created_at",{ascending:false});if(filter!=="TODOS")q=q.eq("estado",filter);const {data,error}=await q;if(error)throw error;return (data||[]) as Inspection[];},refetchInterval:15000});
 const createInspection=useMutation({mutationFn:async()=>{if(!form.centro_salud_id)throw new Error("Seleccione un establecimiento privado registrado.");const {data:{user}}=await supabase.auth.getUser();const {data,error}=await supabase.from("inspecciones_establecimientos").insert({centro_salud_id:form.centro_salud_id,tipo_inspeccion:form.tipo_inspeccion,fecha_programada:form.fecha_programada?new Date(form.fecha_programada).toISOString():null,observaciones:form.observaciones||null,created_by:user?.id||null,inspector_id:user?.id||null}).select().single();if(error)throw error;return data;},onSuccess:()=>{toast({title:"Inspección programada",description:"La inspección ha quedado vinculada al establecimiento privado registrado."});setForm({centro_salud_id:"",tipo_inspeccion:"INICIAL",fecha_programada:"",observaciones:""});setShowNew(false);queryClient.invalidateQueries({queryKey:["inspecciones-establecimientos"]});},onError:(error:any)=>toast({title:"No se pudo programar",description:error?.message||"Error de inspección",variant:"destructive"})});
 const updateInspection=useMutation({mutationFn:async(patch:Partial<Inspection>&{id:string})=>{const {id,...updates}=patch;const {error}=await supabase.from("inspecciones_establecimientos").update(updates).eq("id",id);if(error)throw error;},onSuccess:()=>{toast({title:"Inspección actualizada"});queryClient.invalidateQueries({queryKey:["inspecciones-establecimientos"]});},onError:(error:any)=>toast({title:"No se pudo actualizar",description:error?.message||"Error",variant:"destructive"})});
 const selected=useMemo(()=>inspections.find(i=>i.id===selectedId)||null,[inspections,selectedId]);
 const label=(item:Inspection)=>item.centros_salud?.nombre||item.solicitudes_establecimientos?.nombre_establecimiento||"Establecimiento no identificado";
 const province=(item:Inspection)=>item.centros_salud?.provincia||item.solicitudes_establecimientos?.provincia||"";
 const statusClass=(s:string)=>({PROGRAMADA:"bg-slate-100 text-slate-800",EN_CURSO:"bg-blue-100 text-blue-800",APROBADA:"bg-green-100 text-green-800",CONDICIONADA:"bg-amber-100 text-amber-800",RECHAZADA:"bg-red-100 text-red-800",CANCELADA:"bg-gray-100 text-gray-600"} as Record<string,string>)[s]||"bg-gray-100 text-gray-800";
 return <div className="space-y-6">
  <Card><CardHeader><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><CardTitle className="flex items-center gap-2"><ClipboardCheck className="h-5 w-5"/>Inspecciones de Establecimientos Sanitarios</CardTitle><p className="mt-1 text-sm text-muted-foreground">La agenda se alimenta de todos los establecimientos privados registrados en <strong>centros_salud</strong>, no solo de solicitudes nuevas.</p></div><div className="flex flex-wrap gap-2"><Select value={filter} onValueChange={setFilter}><SelectTrigger className="w-48"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="TODOS">Todos</SelectItem>{STATES.map(s=><SelectItem key={s} value={s}>{s.replace("_"," ")}</SelectItem>)}</SelectContent></Select><Button variant="outline" size="sm" onClick={()=>refetch()}><RefreshCw className="h-4 w-4 mr-2"/>Actualizar</Button><Button size="sm" onClick={()=>setShowNew(v=>!v)}><Plus className="h-4 w-4 mr-2"/>Programar inspección</Button></div></div></CardHeader>{showNew&&<CardContent className="border-t bg-muted/20"><div className="grid gap-4 md:grid-cols-4"><div className="md:col-span-2"><Label>Establecimiento privado registrado</Label><Select value={form.centro_salud_id} onValueChange={value=>setForm(v=>({...v,centro_salud_id:value}))}><SelectTrigger><SelectValue placeholder={centersLoading?"Cargando...":"Seleccione un establecimiento"}/></SelectTrigger><SelectContent>{privateCenters.map((item:any)=><SelectItem key={item.id} value={item.id}>{item.nombre} · {item.provincia}{item.numero_registro?` · ${item.numero_registro}`:""}</SelectItem>)}</SelectContent></Select></div><div><Label>Tipo</Label><Select value={form.tipo_inspeccion} onValueChange={value=>setForm(v=>({...v,tipo_inspeccion:value}))}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{TYPES.map(t=><SelectItem key={t} value={t}>{t}</SelectItem>)}</SelectContent></Select></div><div><Label>Fecha programada</Label><Input type="datetime-local" value={form.fecha_programada} onChange={e=>setForm(v=>({...v,fecha_programada:e.target.value}))}/></div></div><div className="mt-4"><Label>Observaciones iniciales</Label><Textarea value={form.observaciones} onChange={e=>setForm(v=>({...v,observaciones:e.target.value}))} placeholder="Motivo, alcance o instrucciones de la inspección"/></div><div className="mt-4 flex justify-end"><Button onClick={()=>createInspection.mutate()} disabled={createInspection.isPending||privateCenters.length===0}><Plus className="h-4 w-4 mr-2"/>{createInspection.isPending?"Guardando...":"Crear inspección"}</Button></div></CardContent>}</Card>
  <div className="rounded-lg border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-900 flex gap-2"><ShieldCheck className="h-4 w-4 mt-0.5"/><span><strong>{privateCenters.length} establecimientos privados</strong> están disponibles para inspección. Las inspecciones históricas pueden seguir vinculadas a solicitudes, mientras que las nuevas quedan vinculadas directamente al establecimiento registrado.</span></div>
  <div className="grid gap-6 lg:grid-cols-[1.35fr_1fr]"><Card><CardHeader><CardTitle className="text-base">Agenda y expediente <Badge variant="outline" className="ml-2">{inspections.length}</Badge></CardTitle></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-muted/50"><tr><th className="p-3 text-left">Nº</th><th className="p-3 text-left">Establecimiento</th><th className="p-3 text-left">Tipo</th><th className="p-3 text-left">Fecha</th><th className="p-3 text-left">Estado</th></tr></thead><tbody>{isLoading?<tr><td colSpan={5} className="p-8 text-center">Cargando...</td></tr>:inspections.length===0?<tr><td colSpan={5} className="p-8 text-center text-muted-foreground">No hay inspecciones registradas.</td></tr>:inspections.map(item=><tr key={item.id} className={`border-t cursor-pointer ${selectedId===item.id?"bg-muted/50":""}`} onClick={()=>setSelectedId(item.id)}><td className="p-3 font-mono">{item.numero_inspeccion}</td><td className="p-3 font-medium">{label(item)}<div className="text-xs text-muted-foreground">{province(item)}{item.centros_salud?.numero_registro?` · ${item.centros_salud.numero_registro}`:""}</div></td><td className="p-3">{item.tipo_inspeccion}</td><td className="p-3">{item.fecha_programada?new Date(item.fecha_programada).toLocaleString("es-ES"):"—"}</td><td className="p-3"><Badge className={statusClass(item.estado)}>{item.estado.replace("_"," ")}</Badge></td></tr>)}</tbody></table></div></CardContent></Card>
  <Card><CardHeader><CardTitle className="text-base">Expediente de inspección</CardTitle></CardHeader><CardContent>{!selected?<div className="py-10 text-center text-muted-foreground"><Search className="mx-auto h-8 w-8 mb-2"/>Seleccione una inspección.</div>:<div className="space-y-4"><div className="rounded-lg border p-3"><div className="font-semibold">{label(selected)}</div><div className="text-xs text-muted-foreground">{selected.numero_inspeccion} · {selected.tipo_inspeccion}</div></div><div><Label>Estado</Label><Select value={selected.estado} onValueChange={estado=>updateInspection.mutate({id:selected.id,estado})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{STATES.map(s=><SelectItem key={s} value={s}>{s.replace("_"," ")}</SelectItem>)}</SelectContent></Select></div><div><Label>Puntuación</Label><Input type="number" min="0" max="100" step="0.01" value={selected.puntuacion??""} onChange={e=>updateInspection.mutate({id:selected.id,puntuacion:e.target.value===""?null:Number(e.target.value)})}/></div><div><Label>Resultado</Label><Input value={selected.resultado||""} onChange={e=>updateInspection.mutate({id:selected.id,resultado:e.target.value})} placeholder="Conforme, condicionado, no conforme..."/></div><div><Label>Observaciones</Label><Textarea value={selected.observaciones||""} onChange={e=>updateInspection.mutate({id:selected.id,observaciones:e.target.value})}/></div><div><Label>Medidas correctivas</Label><Textarea value={selected.medidas_correctivas||""} onChange={e=>updateInspection.mutate({id:selected.id,medidas_correctivas:e.target.value})}/></div><div><Label>Plazo de corrección</Label><Input type="date" value={selected.plazo_correccion||""} onChange={e=>updateInspection.mutate({id:selected.id,plazo_correccion:e.target.value||null})}/></div><div className="rounded-lg border border-dashed p-3 text-sm text-muted-foreground"><ShieldCheck className="inline h-4 w-4 mr-1"/>El acta, hallazgos y sello de inspección quedan vinculados al expediente.</div><Button variant="outline" className="w-full" onClick={()=>refetch()}><Save className="h-4 w-4 mr-2"/>Actualizar expediente</Button></div>}</CardContent></Card></div>
 </div>;
}
