import { useMemo, useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Switch } from "@/components/ui/switch";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Save, ShieldCheck, RefreshCw, Landmark, LockKeyhole } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { useTesoreriaConceptos, useUpdateTesoreriaConcepto, type TesoreriaConcepto } from "@/hooks/useTesoreriaConceptos";

interface Props { userRole?: string | null }
const MINISTERIAL_ROLES=["RRHH_MINISTERIO","PERSONALIDAD_MINISTERIAL","MINISTERIAL","MINISTERIO","ADMIN_MINISTERIAL","SUPER_ADMINISTRADOR"];

export default function MinisterialTreasuryConfiguration({userRole}:Props){
 const {toast}=useToast();const {data:conceptos=[],isLoading,refetch}=useTesoreriaConceptos();const updateConcepto=useUpdateTesoreriaConcepto();
 const [family,setFamily]=useState("todos");const [drafts,setDrafts]=useState<Record<string,Partial<TesoreriaConcepto>>>({});
 const canEdit=MINISTERIAL_ROLES.includes(String(userRole||"").toUpperCase());
 const visible=useMemo(()=>family==='todos'?conceptos:conceptos.filter(c=>c.tipo_solicitud===family),[conceptos,family]);
 const getValue=(item:TesoreriaConcepto)=>({...item,...(drafts[item.id]||{})});
 const setValue=(item:TesoreriaConcepto,patch:Partial<TesoreriaConcepto>)=>setDrafts(c=>({...c,[item.id]:{...c[item.id],...patch}}));
 const save=async(item:TesoreriaConcepto)=>{if(!canEdit)return;const value=getValue(item);if(!String(value.cuenta_tesoreria||"").trim()){toast({title:"Cuenta de Tesorería obligatoria",description:"Configure la cuenta antes de guardar para evitar Notas de Ingreso incompletas.",variant:"destructive"});return;}try{await updateConcepto.mutateAsync({id:item.id,descripcion:String(value.descripcion||item.descripcion).trim(),monto:Number(value.monto||0),moneda:String(value.moneda||"XAF").toUpperCase(),cuenta_tesoreria:String(value.cuenta_tesoreria).trim(),activo:Boolean(value.activo)});setDrafts(c=>{const n={...c};delete n[item.id];return n});toast({title:"Plantilla actualizada",description:"La configuración se aplicará únicamente a las nuevas Notas de Ingreso. Las notas ya emitidas permanecen inmutables."});}catch(error:any){toast({title:"No se pudo guardar",description:error?.message||"Error de Tesorería",variant:"destructive"})}};
 return <Card><CardHeader><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><CardTitle className="flex items-center gap-2"><Landmark className="h-5 w-5"/>Parámetros generales de Notas de Ingreso</CardTitle><p className="mt-1 text-sm text-muted-foreground">Plantillas ministeriales para cada tipo de solicitud. Se aplican al emitir una nueva nota.</p></div><div className="flex items-center gap-2"><Badge variant="outline"><ShieldCheck className="mr-1 h-3 w-3"/>Ministerio</Badge><Button variant="outline" size="sm" onClick={()=>refetch()}><RefreshCw className="h-4 w-4"/></Button></div></div></CardHeader><CardContent className="space-y-4">
  <div className="rounded-lg border border-blue-200 bg-blue-50 p-4 text-sm text-blue-900 flex gap-3"><LockKeyhole className="h-4 w-4 mt-0.5 shrink-0"/><div><strong>Las Notas de Ingreso emitidas son inmutables.</strong> Aquí solo se modifican las plantillas que utilizarán las futuras solicitudes. Cada nota conserva su importe, concepto, cuenta, PDF y hash para auditoría.</div></div>
  <div className="flex flex-col sm:flex-row gap-3"><Select value={family} onValueChange={setFamily}><SelectTrigger className="w-full sm:w-64"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="todos">Todos los tipos</SelectItem><SelectItem value="profesional">Profesionales sanitarios</SelectItem><SelectItem value="establecimiento">Establecimientos sanitarios</SelectItem></SelectContent></Select><Badge variant="outline" className="self-center">{visible.length} plantillas</Badge></div>
  {!canEdit&&<div className="rounded-md border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">Vista de solo lectura. Solo el Panel Ministerial puede modificar estas plantillas.</div>}
  {isLoading?<div className="py-8 text-center text-muted-foreground">Cargando conceptos...</div>:visible.map(item=>{const value=getValue(item);return <div key={item.id} className="rounded-lg border p-4"><div className="mb-4 flex flex-col gap-2 lg:flex-row lg:items-start lg:justify-between"><div><div className="font-semibold">{item.descripcion}</div><div className="text-xs text-muted-foreground mt-1">Familia: {item.tipo_solicitud} · Tipo: {item.clave_solicitud} · Código: {item.codigo}</div></div><div className="flex items-center gap-2 text-sm"><Switch checked={Boolean(value.activo)} disabled={!canEdit} onCheckedChange={activo=>setValue(item,{activo})}/>{value.activo?"Activo":"Inactivo"}</div></div><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-4"><div className="lg:col-span-2"><label className="mb-1 block text-xs font-medium">Descripción que aparecerá en la Nota</label><Input value={value.descripcion||""} disabled={!canEdit} onChange={e=>setValue(item,{descripcion:e.target.value})}/></div><div><label className="mb-1 block text-xs font-medium">Importe</label><Input type="number" min="0" step="0.01" value={value.monto??0} disabled={!canEdit} onChange={e=>setValue(item,{monto:Number(e.target.value)})}/></div><div><label className="mb-1 block text-xs font-medium">Moneda</label><Input value={value.moneda||"XAF"} disabled={!canEdit} onChange={e=>setValue(item,{moneda:e.target.value.toUpperCase()})}/></div><div className="md:col-span-2 lg:col-span-4"><label className="mb-1 block text-xs font-medium">Cuenta de Tesorería</label><Input value={value.cuenta_tesoreria||""} disabled={!canEdit} placeholder="Código/cuenta de Tesorería" onChange={e=>setValue(item,{cuenta_tesoreria:e.target.value})}/></div></div>{canEdit&&<div className="mt-4 flex justify-end"><Button size="sm" onClick={()=>save(item)} disabled={updateConcepto.isPending}><Save className="mr-2 h-4 w-4"/>Guardar plantilla</Button></div>}</div>})}
 </CardContent></Card>;
}
