// @ts-nocheck
import React,{useState,useEffect} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {Tabs,TabsContent,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {ScrollArea} from '@/components/ui/scroll-area';
import {Button} from '@/components/ui/button';
import {Download,User,FileText,CreditCard,FolderOpen,Stamp} from 'lucide-react';
import {toast} from '@/hooks/use-toast';
import ApprovalLetter from '@/components/registration/ApprovalLetter';
import AdditionalDocuments from '@/components/dashboard/AdditionalDocuments';
import ProfessionalSealCard from '@/components/dashboard/ProfessionalSealCard';
import {type Profesional} from '@/hooks/useProfesionales';
import {useSelloProfesional} from '@/hooks/useSellos';

interface NewProfessionalModalProps{isOpen:boolean;onClose:()=>void;professional:Profesional|null;}

const NewProfessionalModal=({isOpen,onClose,professional}:NewProfessionalModalProps)=>{
 const [additionalDocuments,setAdditionalDocuments]=useState<string[]>(Array.isArray(professional?.documentos_adicionales)?professional.documentos_adicionales:[]);
 const {data:selloProfesional}=useSelloProfesional(professional?.id,professional?.id_profesional_unico);
 useEffect(()=>{setAdditionalDocuments(Array.isArray(professional?.documentos_adicionales)?professional.documentos_adicionales:[]);},[professional]);
 if(!professional)return null;
 const nombre=professional.nombre_completo||`${professional.nombre||''} ${professional.apellidos||''}`.trim();
 const profesionalId=professional.id_profesional_unico||professional.id;
 const formData={...professional,nombre:professional.nombre||'',apellidos:professional.apellidos||'',numero_dip:professional.numero_dip||'',numero_pasaporte:professional.numero_pasaporte||'',area_profesional:professional.area_profesional||'',especialidad:professional.especialidad||'No especificada',titulacion_especifica_1:professional.titulacion_especifica_1||'',institucion_1:professional.institucion_1||'',pais_formacion_1:professional.pais_formacion_1||'',genero:professional.genero||'',nacionalidad:professional.nacionalidad||'',fecha_nacimiento:professional.fecha_nacimiento?new Date(professional.fecha_nacimiento).toLocaleDateString('es-ES'):'N/A',telefono:professional.telefono||'',domicilio:professional.domicilio||'',provincia:professional.provincia||'',distrito:professional.distrito||'',situacion_laboral:professional.situacion_laboral||'',nombre_centro:professional.nombre_centro||'',tipo_sector:professional.tipo_sector||'',codigo_expediente:professional.codigo_expediente,id_profesional_unico:profesionalId,foto_carnet:professional.foto_carnet};
 const downloadCarnet=async()=>{if(!professional.url_carnet){toast({title:'Carnet no disponible',description:'No existe un carnet digital para este profesional.',variant:'destructive'});return;}try{const r=await fetch(professional.url_carnet);if(!r.ok)throw new Error(String(r.status));const b=await r.blob();const u=URL.createObjectURL(b);const a=document.createElement('a');a.href=u;a.download=`carnet-${nombre.replace(/\s+/g,'-')||'profesional'}.svg`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(u);toast({title:'Descarga iniciada',description:'El carnet se está descargando.'});}catch(e){toast({title:'Error de descarga',description:'No se pudo descargar el carnet.',variant:'destructive'});}};
 return <Dialog open={isOpen} onOpenChange={onClose}><DialogContent className="max-w-6xl h-[92vh] flex flex-col"><DialogHeader><DialogTitle className="flex items-center gap-2"><User className="w-5 h-5"/>Detalle del Profesional: {nombre}</DialogTitle></DialogHeader>
  <Tabs defaultValue="details" className="flex-1 flex flex-col mt-3">
   <TabsList className="grid w-full grid-cols-5">
    <TabsTrigger value="details"><User className="w-4 h-4 mr-1"/>Detalles</TabsTrigger>
    <TabsTrigger value="seal"><Stamp className="w-4 h-4 mr-1"/>Sello Profesional</TabsTrigger>
    <TabsTrigger value="approval-letter" disabled={professional.estado_solicitud!=='Pendiente de Firma'}><FileText className="w-4 h-4 mr-1"/>Carta Aprobación</TabsTrigger>
    <TabsTrigger value="carnet" disabled={!professional.url_carnet}><CreditCard className="w-4 h-4 mr-1"/>Carnet Digital</TabsTrigger>
    <TabsTrigger value="documents"><FolderOpen className="w-4 h-4 mr-1"/>Documentos ({additionalDocuments.length})</TabsTrigger>
   </TabsList>
   <div className="flex-1 mt-4 min-h-0">
    <TabsContent value="details" className="h-full mt-0"><ScrollArea className="h-[calc(92vh-190px)] rounded-md border p-5"><div className="space-y-6"><div className="flex flex-col items-center gap-3">{professional.foto_carnet&&<img src={professional.foto_carnet} alt="Foto del profesional" className="w-28 h-36 object-cover border rounded-lg"/>}<div className="text-center"><p className="text-xl font-bold">{nombre}</p><p className="text-sm text-gray-500">ID profesional: {profesionalId}</p></div></div><div className="grid grid-cols-1 md:grid-cols-2 gap-x-8 gap-y-3 text-sm"><p><strong>Expediente:</strong> {professional.codigo_expediente||'—'}</p><p><strong>Estado:</strong> {professional.estado_solicitud||'—'}</p><p><strong>Nacionalidad:</strong> {professional.nacionalidad||'—'}</p><p><strong>DIP/Pasaporte:</strong> {professional.numero_dip||professional.numero_pasaporte||'—'}</p><p><strong>Fecha de nacimiento:</strong> {formData.fecha_nacimiento}</p><p><strong>Género:</strong> {professional.genero||'—'}</p><p><strong>Teléfono:</strong> {professional.telefono||'—'}</p><p><strong>Email:</strong> {professional.email||'—'}</p><p><strong>Área profesional:</strong> {professional.area_profesional||'—'}</p><p><strong>Especialidad:</strong> {professional.especialidad||'—'}</p><p><strong>Titulación:</strong> {professional.titulacion_especifica_1||'—'}</p><p><strong>Institución:</strong> {professional.institucion_1||'—'}</p><p><strong>País de formación:</strong> {professional.pais_formacion_1||'—'}</p><p><strong>Centro de trabajo:</strong> {professional.nombre_centro||'—'}</p><p><strong>Provincia:</strong> {professional.provincia||'—'}</p><p><strong>Distrito:</strong> {professional.distrito||'—'}</p><p><strong>Situación laboral:</strong> {professional.situacion_laboral||'—'}</p></div>{professional.motivo_rechazo&&<div className="border-t pt-4 text-red-700"><strong>Motivo de rechazo:</strong> {professional.motivo_rechazo}</div>}</div></ScrollArea></TabsContent>
    <TabsContent value="seal" className="h-full mt-0"><ScrollArea className="h-[calc(92vh-190px)] rounded-md border p-5"><div className="max-w-4xl mx-auto space-y-5"><div className="flex items-center justify-between"><div><h3 className="text-lg font-semibold">Sello Profesional Sanitario</h3><p className="text-sm text-gray-500">Formato rectangular oficial con los únicos datos identificativos del profesional.</p></div><span className="text-xs px-2 py-1 rounded bg-green-50 text-green-700 border border-green-200">{selloProfesional?.url?'Sello almacenado':'Vista oficial disponible'}</span></div><ProfessionalSealCard name={nombre} professionalId={profesionalId}/><div className="grid grid-cols-1 md:grid-cols-2 gap-3 text-sm"><div className="border rounded-lg p-3"><span className="text-gray-500">Número profesional</span><div className="font-mono font-semibold mt-1">{profesionalId}</div></div><div className="border rounded-lg p-3"><span className="text-gray-500">Nombre</span><div className="font-semibold mt-1">{nombre}</div></div></div></div></ScrollArea></TabsContent>
    <TabsContent value="approval-letter" className="h-full mt-0"><div className="flex justify-end mb-3"><Button onClick={()=>{const el=document.getElementById('approval-letter-content');if(!el)return;toast({title:'Carta preparada',description:'La carta está disponible en la vista para impresión o PDF del navegador.'});}}><Download className="w-4 h-4 mr-2"/>Preparar Carta</Button></div><ScrollArea className="h-[calc(92vh-240px)] rounded-md border bg-gray-50 p-4"><div id="approval-letter-content" className="max-w-[210mm] mx-auto bg-white p-[20mm]" style={{minHeight:'297mm'}}><ApprovalLetter formData={formData}/></div></ScrollArea></TabsContent>
    <TabsContent value="carnet" className="h-full mt-0"><div className="flex justify-between items-center mb-3"><h3 className="text-lg font-semibold">Carnet Digital</h3><Button onClick={downloadCarnet}><Download className="w-4 h-4 mr-2"/>Descargar Carnet</Button></div><div className="h-[calc(92vh-240px)] rounded-md border bg-gray-50 overflow-auto p-4">{professional.url_carnet?<img src={professional.url_carnet} alt="Carnet profesional" className="max-w-3xl w-full mx-auto bg-white border rounded shadow"/>:<div className="text-center py-20 text-gray-500">Carnet digital no disponible.</div>}</div></TabsContent>
    <TabsContent value="documents" className="h-full mt-0"><ScrollArea className="h-[calc(92vh-190px)]"><AdditionalDocuments professionalId={professional.id} existingDocuments={additionalDocuments} onDocumentsUpdate={docs=>setAdditionalDocuments(docs)}/></ScrollArea></TabsContent>
   </div>
  </Tabs>
 </DialogContent></Dialog>;
};
export default NewProfessionalModal;
