// @ts-nocheck
import {useEffect,useMemo,useState} from 'react';
import {Card,CardContent,CardHeader,CardTitle} from '@/components/ui/card';
import {Button} from '@/components/ui/button';
import {Badge} from '@/components/ui/badge';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {Checkbox} from '@/components/ui/checkbox';
import {FileText,Eye,Download,RefreshCw,Save} from 'lucide-react';
import {useProfesionales,type Profesional} from '@/hooks/useProfesionales';
import {useProfesionalesMutations} from '@/hooks/useProfesionalesMutations';
import {useToast} from '@/hooks/use-toast';
import NewProfessionalModal from '@/components/dashboard/NewProfessionalModal';

const STATUS_ORDER=['Recibido','Revisando','Pendiente de Firma','Aprobado','Rechazado'];
const statusClass=(s:string)=>s==='Aprobado'?'bg-green-100 text-green-800 border-green-300':s==='Rechazado'?'bg-red-100 text-red-800 border-red-300':s==='Pendiente de Firma'?'bg-orange-100 text-orange-800 border-orange-300':s==='Revisando'?'bg-blue-100 text-blue-800 border-blue-300':'bg-yellow-100 text-yellow-800 border-yellow-300';

interface Props{userRole:string;initialStatusFilter?:string;onSelectProfessional?:(professional:Profesional)=>void;}
const RequestsPanel=({userRole,initialStatusFilter,onSelectProfessional}:Props)=>{
 const {toast}=useToast();const [statusFilter,setStatusFilter]=useState(initialStatusFilter||'Recibido');const [startDate,setStartDate]=useState('');const [endDate,setEndDate]=useState('');const [selectedIds,setSelectedIds]=useState<string[]>([]);const [bulkStatus,setBulkStatus]=useState('');const [bulkReason,setBulkReason]=useState('');const [selected,setSelected]=useState<Profesional|null>(null);
 const {updateProfesional}=useProfesionalesMutations();
 const {data:profesionales=[],isLoading,refetch,error}=useProfesionales({estado_solicitud:statusFilter==='todos'?'':statusFilter,fecha_solicitud_gte:startDate||undefined,fecha_solicitud_lte:endDate||undefined});
 const list=(profesionales||[]) as Profesional[];const filtered=useMemo(()=>statusFilter==='todos'?list.filter(p=>p.estado_solicitud!=='Aprobado'):list,[list,statusFilter]);
 useEffect(()=>{if(initialStatusFilter!==undefined)setStatusFilter(initialStatusFilter);},[initialStatusFilter]);
 const options=(current:string)=>{const idx=STATUS_ORDER.indexOf(current||'Recibido');return STATUS_ORDER.filter((x,i)=>x!=='Recibido'&&((x==='Rechazado')||i>=idx));};
 const changeStatus=async(p:Profesional,newStatus:string,reason?:string)=>{if(newStatus==='Rechazado'&&!reason?.trim()){toast({title:'Motivo requerido',description:'Debe indicar el motivo del rechazo.',variant:'destructive'});return;}const current=p.estado_solicitud||'Recibido';if(current==='Recibido'&&newStatus==='Aprobado'){toast({title:'Flujo no permitido',description:'Una solicitud Recibida debe pasar primero por Revisando y Pendiente de Firma.',variant:'destructive'});return;}try{await updateProfesional.mutateAsync({id:p.id,updates:{estado_solicitud:newStatus,fecha_revision:newStatus!=='Recibido'&&newStatus!=='Revisando'&&newStatus!=='Rechazado'?new Date().toISOString().slice(0,10):null,fecha_aprobacion:newStatus==='Aprobado'?new Date().toISOString().slice(0,10):null,revisor_solicitud:newStatus!=='Recibido'?'Sistema':null,motivo_rechazo:newStatus==='Rechazado'?reason||null:null}});await refetch();toast({title:'Estado actualizado',description:`${p.nombre_completo||p.nombre} → ${newStatus}`});}catch(e:any){toast({title:'Error',description:e.message||'No se pudo actualizar el estado.',variant:'destructive'});}}
 const exportCsv=()=>{const header=['ID','Nombre','Área','Estado','Provincia','Distrito','Fecha'];const rows=filtered.map(p=>[p.id,p.nombre_completo||`${p.nombre||''} ${p.apellidos||''}`.trim(),p.area_profesional||'',p.estado_solicitud||'',p.provincia||'',p.distrito_sanitario||'',p.created_at?new Date(p.created_at).toLocaleDateString('es-ES'):'']);const csv=[header,...rows].map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(';')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=`Solicitudes_${new Date().toISOString().slice(0,10)}.csv`;a.click();};
 const bulk=async()=>{if(!bulkStatus||selectedIds.length===0)return;const selected=list.filter(p=>selectedIds.includes(p.id));for(const p of selected){if(bulkStatus==='Rechazado'&&!bulkReason.trim())continue;await changeStatus(p,bulkStatus,bulkReason);}setSelectedIds([]);setBulkStatus('');setBulkReason('');};
 return <div className="space-y-6"><Card><CardHeader><CardTitle className="flex items-center justify-between"><span className="flex items-center gap-2"><FileText className="w-5 h-5 text-blue-600"/>Gestión de Solicitudes <Badge variant="outline">{filtered.length}</Badge></span><div className="flex gap-2"><Button variant="outline" size="sm" onClick={()=>refetch()}><RefreshCw className="w-4 h-4"/></Button><Button variant="outline" size="sm" onClick={exportCsv}><Download className="w-4 h-4 mr-1"/>Exportar</Button></div></CardTitle></CardHeader><CardContent><div className="flex flex-col lg:flex-row gap-3"><Select value={statusFilter} onValueChange={setStatusFilter}><SelectTrigger className="w-full lg:w-52"><SelectValue placeholder="Filtrar por estado"/></SelectTrigger><SelectContent><SelectItem value="todos">Todos los estados</SelectItem>{STATUS_ORDER.map(s=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select><Input type="date" value={startDate} onChange={e=>setStartDate(e.target.value)}/><Input type="date" value={endDate} onChange={e=>setEndDate(e.target.value)}/></div></CardContent></Card>
 {selectedIds.length>0&&<Card className="border-blue-200 bg-blue-50"><CardContent className="p-3 flex flex-wrap items-center gap-3"><span className="text-sm font-medium">{selectedIds.length} seleccionadas</span><Select value={bulkStatus} onValueChange={setBulkStatus}><SelectTrigger className="w-48 bg-white"><SelectValue placeholder="Cambiar estado..."/></SelectTrigger><SelectContent>{STATUS_ORDER.filter(x=>x!=='Recibido').map(s=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select>{bulkStatus==='Rechazado'&&<Input className="w-64 bg-white" value={bulkReason} onChange={e=>setBulkReason(e.target.value)} placeholder="Motivo de rechazo"/>}<Button onClick={bulk} disabled={!bulkStatus||updateProfesional.isPending}><Save className="w-4 h-4 mr-1"/>Aplicar</Button></CardContent></Card>}
 <Card><CardContent className="p-0 overflow-x-auto">{error?<div className="p-8 text-center text-red-600">Error al cargar solicitudes. <Button variant="outline" onClick={()=>refetch()}>Reintentar</Button></div>:isLoading?<div className="p-8 text-center"><RefreshCw className="animate-spin inline mr-2"/>Cargando...</div>:<Table><TableHeader><TableRow><TableHead><Checkbox checked={selectedIds.length===filtered.length&&filtered.length>0} onCheckedChange={v=>setSelectedIds(v?filtered.map(p=>p.id):[])}/></TableHead><TableHead>Nombre Completo</TableHead><TableHead>Área</TableHead><TableHead>Centro</TableHead><TableHead>Fecha</TableHead><TableHead>Estado</TableHead><TableHead>Acciones</TableHead></TableRow></TableHeader><TableBody>{filtered.length===0?<TableRow><TableCell colSpan={7} className="text-center p-8 text-gray-500">No hay solicitudes con los filtros seleccionados.</TableCell></TableRow>:filtered.map(p=>{const current=p.estado_solicitud||'Recibido';return <TableRow key={p.id}><TableCell><Checkbox checked={selectedIds.includes(p.id)} onCheckedChange={v=>setSelectedIds(ids=>v?[...new Set([...ids,p.id])]:ids.filter(x=>x!==p.id))}/></TableCell><TableCell className="font-medium">{p.nombre_completo||`${p.nombre||''} ${p.apellidos||''}`.trim()}</TableCell><TableCell>{p.area_profesional||'—'}</TableCell><TableCell>{p.nombre_centro||'—'}</TableCell><TableCell>{p.created_at?new Date(p.created_at).toLocaleDateString('es-ES'):'—'}</TableCell><TableCell><div className="min-w-[190px]"><Select value={current} onValueChange={async v=>{let reason='';if(v==='Rechazado'){reason=window.prompt('Motivo del rechazo:')||'';}await changeStatus(p,v,reason)}}><SelectTrigger className={`border ${statusClass(current)}`}><SelectValue/></SelectTrigger><SelectContent>{current==='Recibido'&&<SelectItem value="Recibido">Recibido</SelectItem>}{options(current).map(s=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select><div className="text-[11px] text-gray-500 mt-1">Cambio directo de estado</div></div></TableCell><TableCell><Button size="sm" variant="outline" onClick={()=>{setSelected(p);onSelectProfessional?.(p)}}><Eye className="w-3 h-3 mr-1"/>Ver</Button></TableCell></TableRow>})}</TableBody></Table>}</CardContent></Card>
 {selected&&<NewProfessionalModal isOpen={!!selected} onClose={()=>setSelected(null)} professional={selected}/>}</div>;
};
export default RequestsPanel;
