import { useMemo, useState } from 'react';
import { Card,CardContent,CardHeader,CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from '@/components/ui/table';
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';
import { Input } from '@/components/ui/input';
import { Dialog,DialogContent,DialogHeader,DialogTitle } from '@/components/ui/dialog';
import { Tabs,TabsContent,TabsList,TabsTrigger } from '@/components/ui/tabs';
import { Building2,Eye,Save,X,RefreshCw,Search,ClipboardCheck,Landmark } from 'lucide-react';
import { useSolicitudesEstablecimientosQuery,useSolicitudesEstablecimientos } from '@/hooks/useSolicitudesEstablecimientos';
import { useToast } from '@/hooks/use-toast';
import EstablishmentInspectionsPanel from '@/components/dashboard/EstablishmentInspectionsPanel';
import MinisterialTreasuryConfiguration from '@/components/dashboard/MinisterialTreasuryConfiguration';

interface Props{userRole:string;defaultEstado?:string;}
const ESTADOS=['Pendiente','Revisando','Pendiente de Firma','Autorizado','Rechazado'];
const statusClass=(estado:string)=>estado==='Autorizado'?'bg-green-100 text-green-800 border-green-300':estado==='Rechazado'?'bg-red-100 text-red-800 border-red-300':estado==='Pendiente de Firma'?'bg-orange-100 text-orange-800 border-orange-300':estado==='Revisando'?'bg-blue-100 text-blue-800 border-blue-300':'bg-yellow-100 text-yellow-800 border-yellow-300';

export default function SolicitudesEstablecimientos({userRole,defaultEstado='Pendiente'}:Props){
 const {toast}=useToast();const [estadoFiltro,setEstadoFiltro]=useState(defaultEstado);const [selected,setSelected]=useState<any>(null);const [editState,setEditState]=useState<Record<string,string>>({});const [rejectReason,setRejectReason]=useState<Record<string,string>>({});const [reviewNotes,setReviewNotes]=useState<Record<string,string>>({});const [search,setSearch]=useState('');
 const {data:solicitudes=[],isLoading,refetch}=useSolicitudesEstablecimientosQuery({estado:estadoFiltro==='todos'?undefined:estadoFiltro});const {actualizarEstadoMutation}=useSolicitudesEstablecimientos();
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return (solicitudes||[]).filter((s:any)=>!q||[s.numero_solicitud,s.nombre_establecimiento,s.director_responsable,s.provincia,s.distrito_sanitario].some(v=>String(v||'').toLowerCase().includes(q)));},[solicitudes,search]);
 const saveState=async(id:string)=>{const estado=editState[id];if(!estado)return;if(estado==='Rechazado'&&!rejectReason[id]?.trim()){toast({title:'Motivo requerido',description:'Debe indicar el motivo del rechazo.',variant:'destructive'});return;}try{await actualizarEstadoMutation.mutateAsync({id,estado,motivo_rechazo:estado==='Rechazado'?rejectReason[id]:undefined,notas_revision:reviewNotes[id]});setEditState(p=>{const n={...p};delete n[id];return n});await refetch();toast({title:'Estado actualizado',description:`La solicitud pasó a “${estado}”.`});}catch(e:any){toast({title:'Error',description:e.message||'No se pudo actualizar el estado.',variant:'destructive'});}};
 if(isLoading)return <div className="flex justify-center p-8"><RefreshCw className="animate-spin mr-2"/>Cargando solicitudes...</div>;
 return <Tabs defaultValue="solicitudes" className="space-y-5">
  <TabsList className="grid w-full grid-cols-3"><TabsTrigger value="solicitudes"><Building2 className="w-4 h-4 mr-2"/>Solicitudes</TabsTrigger><TabsTrigger value="inspecciones"><ClipboardCheck className="w-4 h-4 mr-2"/>Inspecciones</TabsTrigger><TabsTrigger value="tesoreria"><Landmark className="w-4 h-4 mr-2"/>Parámetros Nota de Ingreso</TabsTrigger></TabsList>
  <TabsContent value="solicitudes" className="space-y-6">
   <Card><CardHeader><CardTitle className="flex items-center justify-between"><span className="flex items-center gap-2"><Building2 className="w-5 h-5"/>Gestión completa de Solicitudes de Establecimientos</span><Button variant="outline" size="sm" onClick={()=>refetch()}><RefreshCw className="w-4 h-4 mr-2"/>Actualizar</Button></CardTitle></CardHeader><CardContent><div className="flex flex-col md:flex-row gap-3"><Select value={estadoFiltro} onValueChange={setEstadoFiltro}><SelectTrigger className="w-full md:w-56"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="todos">Todos los estados</SelectItem>{ESTADOS.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select><div className="relative flex-1"><Search className="w-4 h-4 absolute left-3 top-3 text-gray-400"/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar por solicitud, establecimiento, responsable o provincia" className="pl-9"/></div></div></CardContent></Card>
   <Card><CardContent className="p-0"><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Nº Solicitud</TableHead><TableHead>Establecimiento</TableHead><TableHead>Tipo</TableHead><TableHead>Categoría</TableHead><TableHead>Provincia</TableHead><TableHead>Estado</TableHead><TableHead>Fecha</TableHead><TableHead>Acciones</TableHead></TableRow></TableHeader><TableBody>{filtered.length===0?<TableRow><TableCell colSpan={8} className="text-center p-8 text-gray-500">No hay solicitudes con los filtros seleccionados.</TableCell></TableRow>:filtered.map((s:any)=><TableRow key={s.id}><TableCell className="font-mono">{s.numero_solicitud}<div className="text-xs text-gray-500">{s.numero_registro||''}</div></TableCell><TableCell><div className="font-medium">{s.nombre_establecimiento}</div><div className="text-xs text-gray-500">{s.director_responsable}</div></TableCell><TableCell>{s.tipo_solicitud||'REGISTRO'}</TableCell><TableCell>{s.categoria||'—'}</TableCell><TableCell>{s.provincia||'—'}</TableCell><TableCell>{editState[s.id]!==undefined?<div className="space-y-2 min-w-[210px]"><Select value={editState[s.id]} onValueChange={v=>setEditState(p=>({...p,[s.id]:v}))}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{ESTADOS.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select>{editState[s.id]==='Rechazado'&&<Textarea value={rejectReason[s.id]||''} onChange={e=>setRejectReason(p=>({...p,[s.id]:e.target.value}))} placeholder="Motivo del rechazo"/>}<Textarea value={reviewNotes[s.id]||''} onChange={e=>setReviewNotes(p=>({...p,[s.id]:e.target.value}))} placeholder="Notas de revisión (opcional)"/><div className="flex gap-2"><Button size="sm" onClick={()=>saveState(s.id)} disabled={actualizarEstadoMutation.isPending}><Save className="w-3 h-3 mr-1"/>Guardar</Button><Button size="sm" variant="outline" onClick={()=>setEditState(p=>{const n={...p};delete n[s.id];return n})}><X className="w-3 h-3 mr-1"/>Cancelar</Button></div></div>:<div className="flex items-center gap-2"><Badge className={statusClass(s.estado||'Pendiente')}>{s.estado||'Pendiente'}</Badge><Button size="sm" variant="outline" onClick={()=>setEditState(p=>({...p,[s.id]:s.estado||'Pendiente'}))}>Editar</Button></div>}</TableCell><TableCell>{s.fecha_solicitud?new Date(s.fecha_solicitud).toLocaleDateString('es-ES'):'—'}</TableCell><TableCell><Button size="sm" variant="outline" onClick={()=>setSelected(s)}><Eye className="w-3 h-3 mr-1"/>Ver</Button></TableCell></TableRow>)}</TableBody></Table></div></CardContent></Card>
   <Dialog open={!!selected} onOpenChange={()=>setSelected(null)}><DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>Solicitud de establecimiento {selected?.numero_solicitud}</DialogTitle></DialogHeader>{selected&&<div className="space-y-5"><div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm"><div><b>Establecimiento:</b> {selected.nombre_establecimiento}</div><div><b>Tipo de solicitud:</b> {selected.tipo_solicitud||'REGISTRO'}</div><div><b>Categoría:</b> {selected.categoria}</div><div><b>Tipo de servicio:</b> {selected.tipo_servicio}</div><div><b>Provincia:</b> {selected.provincia}</div><div><b>Distrito sanitario:</b> {selected.distrito_sanitario}</div><div><b>Dirección:</b> {selected.direccion}</div><div><b>Director responsable:</b> {selected.director_responsable}</div><div><b>Teléfono:</b> {selected.telefono}</div><div><b>Email:</b> {selected.email}</div><div><b>NIF:</b> {selected.nif}</div><div><b>Documento responsable:</b> {selected.numero_documento}</div><div><b>Número de camas:</b> {selected.numero_camas??'—'}</div><div className="md:col-span-2"><b>Servicios:</b> {Array.isArray(selected.servicios_ofrecidos)?selected.servicios_ofrecidos.join(', '):'—'}</div></div><div className="border-t pt-4"><h4 className="font-semibold mb-2">Flujo de aprobación</h4><div className="flex items-center gap-2"><Badge className={statusClass(selected.estado||'Pendiente')}>{selected.estado||'Pendiente'}</Badge><Button onClick={()=>{setEditState(p=>({...p,[selected.id]:selected.estado||'Pendiente'}));setSelected(null);}}>Editar estado</Button></div></div></div>}</DialogContent></Dialog>
  </TabsContent>
  <TabsContent value="inspecciones"><EstablishmentInspectionsPanel/></TabsContent>
  <TabsContent value="tesoreria"><MinisterialTreasuryConfiguration userRole={userRole}/></TabsContent>
 </Tabs>;
}
