services:
  - type: web
    name: qiandao-sdk
    env: docker
    dockerfilePath: ./rena/Dockerfile
    autoDeploy: true
    port: 8080
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DB_HOST
        scope: run
      - key: DB_PORT
        value: "6543"
        scope: run
      - key: DB_USER
        scope: run
      - key: DB_PASSWORD
        scope: run
      - key: DB_NAME
        value: postgres
        scope: run
