
-- Crear tabla de nacionalidades del mundo
CREATE TABLE IF NOT EXISTS public.nacionalidades_mundo (
  id SERIAL PRIMARY KEY,
  pais TEXT NOT NULL,
  nacionalidad TEXT NOT NULL,
  codigo_iso TEXT
);

-- Insertar nacionalidades del mundo
INSERT INTO public.nacionalidades_mundo (pais, nacionalidad, codigo_iso) VALUES
('Afganistán', 'Afgana', 'AF'),
('Albania', 'Albanesa', 'AL'),
('Alemania', 'Alemana', 'DE'),
('Andorra', 'Andorrana', 'AD'),
('Angola', 'Angoleña', 'AO'),
('Argentina', 'Argentina', 'AR'),
('Armenia', 'Armenia', 'AM'),
('Australia', 'Australiana', 'AU'),
('Austria', 'Austriaca', 'AT'),
('Azerbaiyán', 'Azerbaiyana', 'AZ'),
('Bahamas', 'Bahameña', 'BS'),
('Bangladés', 'Bangladesí', 'BD'),
('Barbados', 'Barbadense', 'BB'),
('Bélgica', 'Belga', 'BE'),
('Belice', 'Beliceña', 'BZ'),
('Benín', 'Beninesa', 'BJ'),
('Bielorrusia', 'Bielorrusa', 'BY'),
('Bolivia', 'Boliviana', 'BO'),
('Bosnia y Herzegovina', 'Bosnia', 'BA'),
('Botsuana', 'Botsuanesa', 'BW'),
('Brasil', 'Brasileña', 'BR'),
('Brunéi', 'Bruneana', 'BN'),
('Bulgaria', 'Búlgara', 'BG'),
('Burkina Faso', 'Burkinesa', 'BF'),
('Burundi', 'Burundesa', 'BI'),
('Bután', 'Butanesa', 'BT'),
('Cabo Verde', 'Caboverdiana', 'CV'),
('Camboya', 'Camboyana', 'KH'),
('Camerún', 'Camerunesa', 'CM'),
('Canadá', 'Canadiense', 'CA'),
('Catar', 'Catarí', 'QA'),
('Chad', 'Chadiana', 'TD'),
('Chile', 'Chilena', 'CL'),
('China', 'China', 'CN'),
('Chipre', 'Chipriota', 'CY'),
('Colombia', 'Colombiana', 'CO'),
('Comoras', 'Comorense', 'KM'),
('Corea del Norte', 'Norcoreana', 'KP'),
('Corea del Sur', 'Surcoreana', 'KR'),
('Costa Rica', 'Costarricense', 'CR'),
('Croacia', 'Croata', 'HR'),
('Cuba', 'Cubana', 'CU'),
('Dinamarca', 'Danesa', 'DK'),
('Dominica', 'Dominiquesa', 'DM'),
('Ecuador', 'Ecuatoriana', 'EC'),
('Egipto', 'Egipcia', 'EG'),
('El Salvador', 'Salvadoreña', 'SV'),
('Emiratos Árabes Unidos', 'Emiratí', 'AE'),
('Eritrea', 'Eritrea', 'ER'),
('Eslovaquia', 'Eslovaca', 'SK'),
('Eslovenia', 'Eslovena', 'SI'),
('España', 'Española', 'ES'),
('Estados Unidos', 'Estadounidense', 'US'),
('Estonia', 'Estonia', 'EE'),
('Etiopía', 'Etíope', 'ET'),
('Filipinas', 'Filipina', 'PH'),
('Finlandia', 'Finlandesa', 'FI'),
('Fiyi', 'Fiyiana', 'FJ'),
('Francia', 'Francesa', 'FR'),
('Gabón', 'Gabonesa', 'GA'),
('Gambia', 'Gambiana', 'GM'),
('Georgia', 'Georgiana', 'GE'),
('Ghana', 'Ghanesa', 'GH'),
('Granada', 'Granadina', 'GD'),
('Grecia', 'Griega', 'GR'),
('Guatemala', 'Guatemalteca', 'GT'),
('Guinea', 'Guineana', 'GN'),
('Guinea Ecuatorial', 'Ecuatoguineana', 'GQ'),
('Guinea-Bisáu', 'Guineana-Bisáu', 'GW'),
('Guyana', 'Guyanesa', 'GY'),
('Haití', 'Haitiana', 'HT'),
('Honduras', 'Hondureña', 'HN'),
('Hungría', 'Húngara', 'HU'),
('India', 'India', 'IN'),
('Indonesia', 'Indonesia', 'ID'),
('Irak', 'Iraquí', 'IQ'),
('Irán', 'Iraní', 'IR'),
('Irlanda', 'Irlandesa', 'IE'),
('Islandia', 'Islandesa', 'IS'),
('Islas Marshall', 'Marshallesa', 'MH'),
('Islas Salomón', 'Salomonense', 'SB'),
('Israel', 'Israelí', 'IL'),
('Italia', 'Italiana', 'IT'),
('Jamaica', 'Jamaicana', 'JM'),
('Japón', 'Japonesa', 'JP'),
('Jordania', 'Jordana', 'JO'),
('Kazajistán', 'Kazaja', 'KZ'),
('Kenia', 'Keniana', 'KE'),
('Kirguistán', 'Kirguisa', 'KG'),
('Kiribati', 'Kiribatiana', 'KI'),
('Kuwait', 'Kuwaití', 'KW'),
('Laos', 'Laosiana', 'LA'),
('Lesoto', 'Lesotense', 'LS'),
('Letonia', 'Letona', 'LV'),
('Líbano', 'Libanesa', 'LB'),
('Liberia', 'Liberiana', 'LR'),
('Libia', 'Libia', 'LY'),
('Liechtenstein', 'Liechtensteiniana', 'LI'),
('Lituania', 'Lituana', 'LT'),
('Luxemburgo', 'Luxemburguesa', 'LU'),
('Madagascar', 'Malgache', 'MG'),
('Malasia', 'Malasia', 'MY'),
('Malaui', 'Malauí', 'MW'),
('Maldivas', 'Maldiva', 'MV'),
('Malí', 'Maliense', 'ML'),
('Malta', 'Maltesa', 'MT'),
('Marruecos', 'Marroquí', 'MA'),
('Mauricio', 'Mauriciana', 'MU'),
('Mauritania', 'Mauritana', 'MR'),
('México', 'Mexicana', 'MX'),
('Micronesia', 'Micronesia', 'FM'),
('Moldavia', 'Moldava', 'MD'),
('Mónaco', 'Monegasca', 'MC'),
('Mongolia', 'Mongola', 'MN'),
('Montenegro', 'Montenegrina', 'ME'),
('Mozambique', 'Mozambiqueña', 'MZ'),
('Myanmar', 'Birmana', 'MM'),
('Namibia', 'Namibia', 'NA'),
('Nauru', 'Nauruana', 'NR'),
('Nepal', 'Nepalí', 'NP'),
('Nicaragua', 'Nicaragüense', 'NI'),
('Níger', 'Nigerina', 'NE'),
('Nigeria', 'Nigeriana', 'NG'),
('Noruega', 'Noruega', 'NO'),
('Nueva Zelanda', 'Neozelandesa', 'NZ'),
('Omán', 'Omaní', 'OM'),
('Países Bajos', 'Neerlandesa', 'NL'),
('Pakistán', 'Pakistaní', 'PK'),
('Palaos', 'Palauana', 'PW'),
('Panamá', 'Panameña', 'PA'),
('Papúa Nueva Guinea', 'Papúa', 'PG'),
('Paraguay', 'Paraguaya', 'PY'),
('Perú', 'Peruana', 'PE'),
('Polonia', 'Polaca', 'PL'),
('Portugal', 'Portuguesa', 'PT'),
('Reino Unido', 'Británica', 'GB'),
('República Centroafricana', 'Centroafricana', 'CF'),
('República Checa', 'Checa', 'CZ'),
('República Democrática del Congo', 'Congoleña', 'CD'),
('República Dominicana', 'Dominicana', 'DO'),
('República del Congo', 'Congoleña', 'CG'),
('Ruanda', 'Ruandesa', 'RW'),
('Rumania', 'Rumana', 'RO'),
('Rusia', 'Rusa', 'RU'),
('Samoa', 'Samoana', 'WS'),
('San Cristóbal y Nieves', 'Sanctristobaleña', 'KN'),
('San Marino', 'Sanmarinense', 'SM'),
('San Vicente y las Granadinas', 'Sanvicentina', 'VC'),
('Santa Lucía', 'Santalucense', 'LC'),
('Santo Tomé y Príncipe', 'Santotomense', 'ST'),
('Senegal', 'Senegalesa', 'SN'),
('Serbia', 'Serbia', 'RS'),
('Seychelles', 'Seychellense', 'SC'),
('Sierra Leona', 'Sierraleonesa', 'SL'),
('Singapur', 'Singapurense', 'SG'),
('Siria', 'Siria', 'SY'),
('Somalia', 'Somalí', 'SO'),
('Sri Lanka', 'Ceilanesa', 'LK'),
('Suazilandia', 'Suazi', 'SZ'),
('Sudáfrica', 'Sudafricana', 'ZA'),
('Sudán', 'Sudanesa', 'SD'),
('Sudán del Sur', 'Sursudanesa', 'SS'),
('Suecia', 'Sueca', 'SE'),
('Suiza', 'Suiza', 'CH'),
('Surinam', 'Surinamesa', 'SR'),
('Tailandia', 'Tailandesa', 'TH'),
('Tanzania', 'Tanzana', 'TZ'),
('Tayikistán', 'Tayika', 'TJ'),
('Timor Oriental', 'Timorense', 'TL'),
('Togo', 'Togolesa', 'TG'),
('Tonga', 'Tongana', 'TO'),
('Trinidad y Tobago', 'Trinitense', 'TT'),
('Túnez', 'Tunecina', 'TN'),
('Turkmenistán', 'Turkmena', 'TM'),
('Turquía', 'Turca', 'TR'),
('Tuvalu', 'Tuvaluana', 'TV'),
('Ucrania', 'Ucraniana', 'UA'),
('Uganda', 'Ugandesa', 'UG'),
('Uruguay', 'Uruguaya', 'UY'),
('Uzbekistán', 'Uzbeka', 'UZ'),
('Vanuatu', 'Vanuatuense', 'VU'),
('Venezuela', 'Venezolana', 'VE'),
('Vietnam', 'Vietnamita', 'VN'),
('Yemen', 'Yemení', 'YE'),
('Yibuti', 'Yibutiana', 'DJ'),
('Zambia', 'Zambiana', 'ZM'),
('Zimbabue', 'Zimbabuense', 'ZW');

-- Agregar campos necesarios a la tabla profesionales_sanitarios
ALTER TABLE public.profesionales_sanitarios 
ADD COLUMN IF NOT EXISTS periodo_formacion TEXT,
ADD COLUMN IF NOT EXISTS año_fin_formacion INTEGER,
ADD COLUMN IF NOT EXISTS categoria_titulacion TEXT,
ADD COLUMN IF NOT EXISTS situacion_laboral TEXT DEFAULT 'Activo',
ADD COLUMN IF NOT EXISTS documentos_cargados JSONB DEFAULT '[]'::jsonb;

-- Actualizar trigger para calcular año de finalización automáticamente
CREATE OR REPLACE FUNCTION public.calcular_año_fin_formacion()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  -- Extraer año de finalización del periodo de formación
  IF NEW.periodo_formacion IS NOT NULL THEN
    -- Buscar patrón como "2018-2022" o "2018 - 2022"
    NEW.año_fin_formacion := CAST(
      SPLIT_PART(
        REGEXP_REPLACE(NEW.periodo_formacion, '.*[^0-9]([0-9]{4})[^0-9]*$', '\1'),
        '-', -1
      ) AS INTEGER
    );
    
    -- Si no se puede extraer, usar año_graduacion como fallback
    IF NEW.año_fin_formacion IS NULL OR NEW.año_fin_formacion = 0 THEN
      NEW.año_fin_formacion := NEW.año_graduacion;
    END IF;
  END IF;
  
  RETURN NEW;
END;
$$;

-- Crear trigger para calcular año de finalización
DROP TRIGGER IF EXISTS trigger_calcular_año_fin_formacion ON public.profesionales_sanitarios;
CREATE TRIGGER trigger_calcular_año_fin_formacion
  BEFORE INSERT OR UPDATE ON public.profesionales_sanitarios
  FOR EACH ROW EXECUTE FUNCTION public.calcular_año_fin_formacion();
