// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://wdieynendfjbkbhfovrx.supabase.co";
export const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndkaWV5bmVuZGZqYmtiaGZvdnJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3ODI5MjEsImV4cCI6MjA2NjM1ODkyMX0.yFnLHavy8wzVjlg3sAI2mEG-XGDCV5FSr7OQsMefxL8";

// Validate environment variables
if (!SUPABASE_URL) {
  console.error('❌ VITE_SUPABASE_URL is not defined');
  throw new Error('Missing VITE_SUPABASE_URL environment variable');
}

if (!SUPABASE_PUBLISHABLE_KEY) {
  console.error('❌ VITE_SUPABASE_ANON_KEY is not defined');
  throw new Error('Missing VITE_SUPABASE_ANON_KEY environment variable');
}

console.log('✅ Supabase client initialized with:', {
  url: SUPABASE_URL,
  hasKey: SUPABASE_PUBLISHABLE_KEY ? 'Yes' : 'No',
  keyLength: SUPABASE_PUBLISHABLE_KEY?.length || 0
});

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

const resilientFetch: typeof fetch = async (input, init = {}) => {
  const maxAttempts = 3;
  const baseTimeoutMs = 12000;
  let lastError: any = null;

  for (let attempt = 0; attempt < maxAttempts; attempt++) {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), baseTimeoutMs * (attempt + 1));
    try {
      const resp = await fetch(input, {
        ...init,
        cache: 'no-store',
        keepalive: true,
        signal: controller.signal,
        headers: {
          ...(init.headers || {}),
          'X-Client-Info': 'guinea-salud-dashboard',
        },
        mode: 'cors',
      } as RequestInit);

      clearTimeout(timeout);

      // Retry on transient server/network statuses
      if ([429, 502, 503, 504].includes(resp.status)) {
        lastError = new Error(`HTTP ${resp.status}`);
        await sleep(300 * (attempt + 1));
        continue;
      }
      return resp;
    } catch (err: any) {
      clearTimeout(timeout);
      lastError = err;
      const msg = (err?.name === 'AbortError') ? 'Timeout' : (err?.message || 'Failed to fetch');
      console.warn(`resilientFetch attempt ${attempt + 1}/${maxAttempts} -> ${msg}`);
      if (attempt < maxAttempts - 1) {
        await sleep(300 * (attempt + 1));
        continue;
      }
      throw err;
    }
  }
  throw lastError || new Error('Unknown fetch error');
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
    storageKey: 'supabase.auth.token',
    storage: window.localStorage,
    flowType: 'pkce',
  },
  global: {
    headers: {
      'X-Client-Info': 'guinea-salud-dashboard',
    },
  },
  db: {
    schema: 'public',
  },
  realtime: {
    params: {
      eventsPerSecond: 10,
    },
  },
});

// Enhanced connection monitoring
let connectionAttempts = 0;
const MAX_CONNECTION_ATTEMPTS = 5;

// Add connection event listeners
supabase.auth.onAuthStateChange((event, session) => {
  console.log('🔐 Auth state changed:', event, session?.user?.id ? 'User logged in' : 'No user');

  if (event === 'SIGNED_IN') {
    connectionAttempts = 0; // Reset on successful auth
  }
});

// Create a wrapper for better error handling
export const executeSupabaseQuery = async <T>(
  queryFn: () => Promise<{ data: T | null; error: any }>,
  context: string = 'Unknown query'
): Promise<{ data: T | null; error: any }> => {
  try {
    console.log(`🔍 Executing Supabase query: ${context}`);
    const startTime = Date.now();

    const result = await queryFn();

    const duration = Date.now() - startTime;
    console.log(`⏱️ Query "${context}" completed in ${duration}ms`);

    if (result.error) {
      console.error(`❌ Query "${context}" failed:`, result.error);
      connectionAttempts++;

      if (connectionAttempts >= MAX_CONNECTION_ATTEMPTS) {
        console.error(`🚨 Max connection attempts (${MAX_CONNECTION_ATTEMPTS}) reached for context: ${context}`);
      }
    } else {
      connectionAttempts = 0; // Reset on success
    }

    return result;
  } catch (error: any) {
    console.error(`💥 Query "${context}" threw exception:`, error);
    connectionAttempts++;

    // Convert exceptions to Supabase-like error format
    return {
      data: null,
      error: {
        message: error.message || 'Unknown error',
        details: error.stack || error.toString(),
        hint: 'Check network connectivity and Supabase configuration',
        code: error.code || 'QUERY_EXCEPTION'
      }
    };
  }
};

// Export connection status
export const getConnectionStatus = () => ({
  attempts: connectionAttempts,
  isHealthy: connectionAttempts < MAX_CONNECTION_ATTEMPTS,
  maxAttempts: MAX_CONNECTION_ATTEMPTS
});
