// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { supabase as hosixSupabase, getConnectionStatus as getHosixConnectionStatus } from './hosixClient';
export const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://wdieynendfjbkbhfovrx.supabase.co";
export const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndkaWV5bmVuZGZqYmtiaGZvdnJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3ODI5MjEsImV4cCI6MjA2NjM1ODkyMX0.yFnLHavy8wVjlg3sAI2mEG-XGDCV5FSr7OQsMefxL8";
if (!SUPABASE_URL) throw new Error('Missing VITE_SUPABASE_URL environment variable');
if (!SUPABASE_PUBLISHABLE_KEY) throw new Error('Missing VITE_SUPABASE_ANON_KEY environment variable');
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
const nativeFetch: typeof fetch = typeof window!=='undefined' ? window.fetch.bind(window) : fetch;
const resilientFetch: typeof fetch = async (input, init={})=>{
  const maxAttempts=3, baseTimeoutMs=12000; let lastError:any=null;
  const mergedHeaders=new Headers(input instanceof Request ? input.headers : undefined);
  new Headers(init.headers||{}).forEach((value,key)=>mergedHeaders.set(key,value));
  mergedHeaders.set('X-Client-Info','guinea-salud-dashboard');
  try { const type=typeof window!=='undefined'?window.localStorage.getItem('professional_request_type'):null; if(type) mergedHeaders.set('X-Renaprosa-Request-Type',type); } catch(_) {}
  try { const type=typeof window!=='undefined'?window.localStorage.getItem('establishment_request_type'):null; if(type) mergedHeaders.set('X-Renaprosa-Establishment-Type',type); } catch(_) {}
  for(let attempt=0;attempt<maxAttempts;attempt++){
    const controller=new AbortController(); const timeout=setTimeout(()=>controller.abort(),baseTimeoutMs*(attempt+1));
    try { const resp=await nativeFetch(input,{...init,cache:'no-store',keepalive:true,signal:controller.signal,headers:mergedHeaders,mode:'cors'} as RequestInit); clearTimeout(timeout); if([429,502,503,504].includes(resp.status)){lastError=new Error(`HTTP ${resp.status}`);await sleep(300*(attempt+1));continue;} return resp; }
    catch(err:any){clearTimeout(timeout);lastError=err;if(attempt<maxAttempts-1){await sleep(300*(attempt+1));continue;}throw err;}
  }
  throw lastError||new Error('Unknown fetch error');
};
export const rootSupabase=createClient<Database>(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{autoRefreshToken:true,persistSession:true,detectSessionInUrl:true,storageKey:'supabase.auth.token',storage:window.localStorage,flowType:'pkce'},global:{headers:{'X-Client-Info':'guinea-salud-dashboard'},fetch:resilientFetch},db:{schema:'public'},realtime:{params:{eventsPerSecond:10}}});
const isHosixPath=()=>typeof window!=='undefined'&&window.location.pathname.startsWith('/hosix'); const getCurrentSupabase=()=>isHosixPath()?hosixSupabase:rootSupabase;
export const supabase=new Proxy(rootSupabase,{get(target,prop,receiver){const current=getCurrentSupabase();const value=Reflect.get(current,prop,current);return typeof value==='function'?value.bind(current):value;}}) as typeof rootSupabase;
let connectionAttempts=0; const MAX_CONNECTION_ATTEMPTS=5;
rootSupabase.auth.onAuthStateChange((event,session)=>{console.log('🔐 Auth state changed:',event,session?.user?.id?'User logged in':'No user');if(event==='SIGNED_IN')connectionAttempts=0;});
export const executeSupabaseQuery=async<T>(queryFn:()=>Promise<{data:T|null;error:any}>,context='Unknown query')=>{try{const start=Date.now();const result=await queryFn();console.log(`⏱️ Query "${context}" completed in ${Date.now()-start}ms`);if(result.error)connectionAttempts++;else connectionAttempts=0;return result;}catch(error:any){connectionAttempts++;return{data:null,error:{message:error.message||'Unknown error',details:error.stack||error.toString(),hint:'Check network connectivity and Supabase configuration',code:error.code||'QUERY_EXCEPTION'}};}};
const getRootConnectionStatus=()=>({attempts:connectionAttempts,isHealthy:connectionAttempts<MAX_CONNECTION_ATTEMPTS,maxAttempts:MAX_CONNECTION_ATTEMPTS});
export const getConnectionStatus=()=>isHosixPath()?getHosixConnectionStatus():getRootConnectionStatus();
try{if(typeof window!=='undefined'&&typeof window.fetch==='function'){(window as any).originalFetch=window.fetch;(window as any).fetch=resilientFetch;}}catch(e){console.warn('Could not replace global fetch:',e);}
