import React from 'react';
import { supabase } from '@/integrations/supabase/client';

type FuncionarioStatus = 'nombrado' | 'no_nombrado';
type NullableString = string | null | undefined;
interface RequestLetterData { nombre:string; apellidos:string; nacionalidad:string; numero_dip?:NullableString; numero_pasaporte?:NullableString; domicilio?:NullableString; distrito?:NullableString; provincia?:NullableString; telefono?:NullableString; area_profesional?:NullableString; especialidad?:NullableString; titulacion_especifica_1?:NullableString; institucion_1?:NullableString; pais_formacion_1?:NullableString; periodo_formacion?:NullableString; situacion_laboral?:NullableString; funcion_publica?:boolean|null; estatus_funcionario?:FuncionarioStatus|null; numero_funcionario?:NullableString; fecha_nombramiento?:NullableString; fecha_inicio_trabajo?:NullableString; nombre_centro?:NullableString; categoria_centro?:NullableString; tipo_sector?:NullableString; distrito_sanitario?:NullableString; pertenece_brigada_medica?:boolean|null; tipo_cooperacion?:NullableString; tipo_solicitud?:NullableString; codigo_expediente?:NullableString; sello_expediente_url?:NullableString; }
const normalizeTipo=(value?:NullableString)=>{const raw=String(value||'REGISTRO').trim().toUpperCase();if(raw.includes('RENOV'))return'RENOVACION';if(raw.includes('EXTRAV'))return'EXTRAVIO';if(raw.includes('DETER'))return'DETERIORO';if(raw.includes('DUPLIC'))return'DUPLICADO';if(raw.includes('ACTUAL'))return'ACTUALIZACION';return'REGISTRO';};
const labels:any={REGISTRO:'Registro inicial de acreditación profesional sanitaria',RENOVACION:'Renovación de acreditación profesional sanitaria',EXTRAVIO:'Solicitud de duplicado por extravío del documento profesional',DETERIORO:'Solicitud de duplicado por deterioro del documento profesional',DUPLICADO:'Solicitud de duplicado de acreditación profesional sanitaria',ACTUALIZACION:'Actualización de datos de acreditación profesional sanitaria'};
const purpose:any={REGISTRO:'mi acreditación profesional sanitaria',RENOVACION:'la renovación de mi acreditación profesional sanitaria',EXTRAVIO:'la expedición de un duplicado de mi acreditación profesional sanitaria por extravío',DETERIORO:'la expedición de un duplicado de mi acreditación profesional sanitaria por deterioro',DUPLICADO:'la expedición de un duplicado de mi acreditación profesional sanitaria',ACTUALIZACION:'la actualización de mis datos de acreditación profesional sanitaria'};
const dateLong=(v?:NullableString)=>{if(!v)return null;const d=new Date(v);return Number.isNaN(d.getTime())?null:d.toLocaleDateString('es-ES',{year:'numeric',month:'long',day:'numeric'});};
const RequestLetter=({formData}: {formData:RequestLetterData})=>{
  const [sello,setSello]=React.useState(formData.sello_expediente_url||'');
  const [tipo,setTipo]=React.useState(normalizeTipo(formData.tipo_solicitud));
  React.useEffect(()=>{let cancelled=false;try{const stored=localStorage.getItem('professional_request_type');if(!formData.tipo_solicitud&&stored)setTipo(normalizeTipo(stored));}catch(_){} if(!sello&&formData.codigo_expediente){supabase.from('sellos_expedientes').select('url_sello').eq('codigo_expediente',formData.codigo_expediente).order('created_at',{ascending:false}).limit(1).maybeSingle().then(({data})=>{if(!cancelled&&data?.url_sello)setSello(data.url_sello);});} return()=>{cancelled=true;};},[formData.codigo_expediente,formData.tipo_solicitud,sello]);
  const today=new Date().toLocaleDateString('es-ES',{year:'numeric',month:'long',day:'numeric'});const identificacion=formData.numero_dip?`número de DIP ${formData.numero_dip}`:formData.numero_pasaporte?`número de pasaporte ${formData.numero_pasaporte}`:'documento de identificación vigente';const nombramiento=dateLong(formData.fecha_nombramiento);const inicio=dateLong(formData.fecha_inicio_trabajo);
  return <div className="space-y-4"><div id="letter-content" className="max-w-[210mm] mx-auto bg-white" style={{padding:'15mm 20mm',minHeight:'297mm',fontSize:'10.5px',lineHeight:'1.4'}}>
    <div className="text-center mb-4"><h1 className="text-base font-bold">REPÚBLICA DE GUINEA ECUATORIAL</h1><h2 className="text-sm font-semibold">MINISTERIO DE SANIDAD Y BIENESTAR SOCIAL</h2><div className="border-b-2 border-black mt-2 mb-3"/><div className="inline-block border border-gray-400 px-3 py-1 text-xs font-bold">EXPEDIENTE: {formData.codigo_expediente||'PENDIENTE'}</div></div>
    <div className="text-right mb-4">Malabo, {today}</div><div className="mb-3"><p className="font-semibold text-sm">AL SEÑOR MINISTRO DE SANIDAD Y BIENESTAR SOCIAL</p><p className="text-sm">REPÚBLICA DE GUINEA ECUATORIAL</p><p className="mt-1 text-sm"><b>ASUNTO:</b> {labels[tipo]}</p></div>
    <div className="mb-5 space-y-2.5 text-justify"><p>Yo, <b>{formData.nombre} {formData.apellidos}</b>, de nacionalidad <b>{formData.nacionalidad}</b>, con {identificacion}, con domicilio en <b>{formData.domicilio}{formData.distrito?`, ${formData.distrito}`:''}{formData.provincia?`, ${formData.provincia}`:''}</b>, y teléfono <b>{formData.telefono}</b>, comparezco ante usted para solicitar <b>{purpose[tipo]}</b>.</p>
      {(tipo==='REGISTRO'||tipo==='RENOVACION'||tipo==='ACTUALIZACION')&&<p>Soy profesional en el área de <b>{formData.area_profesional}</b>{formData.especialidad?<> , con especialización en <b>{formData.especialidad}</b></>:null}, con titulación de <b>{formData.titulacion_especifica_1}</b> obtenida en <b>{formData.institucion_1}</b>, <b>{formData.pais_formacion_1}</b>, período <b>{formData.periodo_formacion}</b>.</p>}
      {(tipo==='EXTRAVIO'||tipo==='DETERIORO'||tipo==='DUPLICADO')&&<p>La presente solicitud tiene por objeto sustituir el documento profesional anterior. Motivo del duplicado: <b>{tipo==='EXTRAVIO'?'extravío':tipo==='DETERIORO'?'deterioro':'duplicado'}</b>.</p>}
      <p>Mi situación laboral es <b>{formData.situacion_laboral}</b>{formData.estatus_funcionario?<> y soy funcionario público {formData.estatus_funcionario==='nombrado'?<>nombrado{nombramiento?`, con nombramiento de fecha ${nombramiento}`:''}{formData.numero_funcionario?`, número ${formData.numero_funcionario}`:''}</>:<>no nombrado{inicio?`, desempeñándome desde el ${inicio}`:''}</>}</>:null}{formData.nombre_centro?<> , prestando servicios en <b>{formData.nombre_centro}</b></>:null}.</p>
      <p>Adjunto la documentación requerida y me comprometo a cumplir los requisitos establecidos por el Ministerio de Sanidad y Bienestar Social.</p></div>
    <div className="mt-8 flex justify-between items-end"><div className="text-xs text-gray-600">Trámite: <b>{labels[tipo]}</b><br/>Generado: {today}</div>{sello?<img src={sello} alt="Sello de expediente" className="w-28 h-28 object-contain"/>:<div className="w-28 h-28 border border-dashed border-gray-400 flex items-center justify-center text-[9px] text-gray-500 text-center">SELLO DE EXPEDIENTE</div>}<div className="text-center"><p className="mb-8">Atentamente,</p><div className="border-t border-black w-60 mx-auto mb-1"/><b>{formData.nombre} {formData.apellidos}</b><p className="text-xs">{formData.area_profesional||'Profesional sanitario'}</p></div></div>
  </div></div>;
};
export default RequestLetter;
