import React from 'react';

const Field=({label,value}:{label:string;value:any})=><div className="border-b border-[#d7e3e6] pb-2"><div className="text-[9px] font-bold uppercase tracking-wide text-[#55717a]">{label}</div><div className="mt-1 text-[12px] text-[#17343b]">{value||'—'}</div></div>;

const SolicitudSummaryPage=({formData}:{formData:any})=><div className="pdf-page bg-white w-[210mm] min-h-[297mm] box-border px-[16mm] py-[13mm] text-[#17343b]" style={{fontFamily:'Arial, Helvetica, sans-serif'}}>
  <header className="text-center border-b-2 border-[#16859a] pb-4"><div className="text-[14px] font-bold tracking-wide">REPÚBLICA DE GUINEA ECUATORIAL</div><div className="text-[17px] font-bold text-[#0d7085] mt-1">MINISTERIO DE SANIDAD E INFRAESTRUCTURAS SANITARIAS</div><div className="text-[21px] font-extrabold mt-3 tracking-wide">SOLICITUD DE ACREDITACIÓN PROFESIONAL SANITARIA</div>{formData.codigo_expediente&&<div className="inline-block mt-3 border border-[#9bbcc2] rounded px-4 py-1 text-[11px] font-bold">EXPEDIENTE: {formData.codigo_expediente}</div>}</header>
  <div className="grid grid-cols-[90px_1fr] gap-5 mt-5"><div>{formData.foto_carnet_base64?<img src={formData.foto_carnet_base64} alt="Foto carnet" className="w-[90px] h-[120px] object-cover border border-[#b8d0d5] rounded"/>:<div className="w-[90px] h-[120px] border border-dashed border-[#b8d0d5] rounded flex items-center justify-center text-[9px] text-[#55717a]">FOTO</div>}</div><div className="grid grid-cols-2 gap-x-6 gap-y-3"><Field label="Nombre completo" value={`${formData.nombre||''} ${formData.apellidos||''}`}/><Field label="Género" value={formData.genero}/><Field label="Fecha de nacimiento" value={formData.fecha_nacimiento}/><Field label="Nacionalidad" value={formData.nacionalidad}/><Field label="DIP / Pasaporte" value={formData.numero_dip||formData.numero_pasaporte}/><Field label="Teléfono" value={formData.telefono}/></div></div>
  <section className="mt-5"><div className="text-[12px] font-bold text-[#0d7085] border-b border-[#c6dfe3] pb-2">DATOS PROFESIONALES</div><div className="grid grid-cols-2 gap-x-7 gap-y-3 mt-3"><Field label="Área profesional" value={formData.area_profesional}/><Field label="Especialidad" value={formData.especialidad}/><Field label="Categoría de titulación" value={formData.categoria_titulacion}/><Field label="Titulación" value={formData.titulacion_especifica_1}/><Field label="Institución" value={formData.institucion_1}/><Field label="País de formación" value={formData.pais_formacion_1}/><Field label="Período de formación" value={formData.periodo_formacion}/><Field label="Situación laboral" value={formData.situacion_laboral}/></div></section>
  <section className="mt-5"><div className="text-[12px] font-bold text-[#0d7085] border-b border-[#c6dfe3] pb-2">DATOS LABORALES Y DOMICILIO</div><div className="grid grid-cols-2 gap-x-7 gap-y-3 mt-3"><Field label="Centro de trabajo" value={formData.nombre_centro}/><Field label="Categoría del centro" value={formData.categoria_centro}/><Field label="Tipo de sector" value={formData.tipo_sector}/><Field label="Distrito sanitario" value={formData.distrito_sanitario}/><Field label="Domicilio" value={formData.domicilio}/><Field label="Provincia" value={formData.provincia}/><Field label="Distrito" value={formData.distrito}/><Field label="Fecha de solicitud" value={new Date().toLocaleDateString('es-ES')}/></div></section>
  <div className="mt-7 border-2 border-[#16859a] rounded-lg p-4"><div className="text-[11px] font-bold text-[#0d7085]">DECLARACIÓN</div><p className="mt-2 text-[10.5px] leading-5 text-justify">El solicitante declara que los datos consignados en esta solicitud son correctos y que aporta la documentación requerida para la tramitación de su acreditación profesional sanitaria.</p><div className="mt-5 flex justify-between items-end"><div className="text-[9px] text-[#55717a]">Código de expediente<br/><b>{formData.codigo_expediente||'PENDIENTE'}</b></div><div className="text-center"><div className="border-t border-black w-48 mb-1"/><div className="text-[9px]">Firma del solicitante</div></div></div></div>
  <footer className="mt-5 pt-3 border-t border-[#c8d6d9] flex justify-between text-[8.5px] text-[#6a7f84]"><span>Documento de solicitud · Guinea Ecuatorial Salud</span><span>MINISTERIO DE SANIDAD E INFRAESTRUCTURAS SANITARIAS</span></footer>
</div>;

export default SolicitudSummaryPage;
